<?php
declare(strict_types=1);

namespace dev\winterframework\data\memcache\mcd;

/**
 * @method int getResultCode()
 * @method string getResultMessage()
 * @method mixed get(string $key, ?callable $cache_cb = null, int $get_flags = 0)
 * @method mixed getByKey(string $server_key, string $key, ?callable $cache_cb = null, int $get_flags = 0)
 * @method false|array getMulti(array $keys, int $get_flags = 0)
 * @method false|array getMultiByKey(string $server_key, array $keys, int $get_flags = 0)
 * @method bool getDelayed(array $keys, bool $with_cas = false, ?callable $value_cb = null)
 * @method bool getDelayedByKey(string $server_key, array $keys, bool $with_cas = false, ?callable $value_cb = null)
 * @method false|array fetch()
 * @method false|array fetchAll()
 * @method bool set(string $key, mixed $value, int $expiration = 0)
 * @method bool setByKey(string $server_key, string $key, mixed $value, int $expiration = 0)
 * @method bool touch(string $key, int $expiration = 0)
 * @method bool touchByKey(string $server_key, string $key, int $expiration = 0)
 * @method bool setMulti(array $items, int $expiration = 0)
 * @method bool setMultiByKey(string $server_key, array $items, int $expiration = 0)
 * @method bool cas(string $cas_token, string $key, mixed $value, int $expiration = 0)
 * @method bool casByKey(string $cas_token, string $server_key, string $key, mixed $value, int $expiration = 0)
 * @method bool add(string $key, mixed $value, int $expiration = 0)
 * @method bool addByKey(string $server_key, string $key, mixed $value, int $expiration = 0)
 * @method bool|null append(string $key, string $value)
 * @method bool|null appendByKey(string $server_key, string $key, string $value)
 * @method bool|null prepend(string $key, string $value)
 * @method bool|null prependByKey(string $server_key, string $key, string $value)
 * @method bool replace(string $key, mixed $value, int $expiration = 0)
 * @method bool replaceByKey(string $server_key, string $key, mixed $value, int $expiration = 0)
 * @method bool delete(string $key, int $time = 0)
 * @method array deleteMulti(array $keys, int $time = 0)
 * @method bool deleteByKey(string $server_key, string $key, int $time = 0)
 * @method array deleteMultiByKey(string $server_key, array $keys, int $time = 0)
 * @method false|int increment(string $key, int $offset = 1, int $initial_value = 0, int $expiry = 0)
 * @method false|int decrement(string $key, int $offset = 1, int $initial_value = 0, int $expiry = 0)
 * @method false|int incrementByKey(string $server_key, string $key, int $offset = 1, int $initial_value = 0, int $expiry = 0)
 * @method false|int decrementByKey(string $server_key, string $key, int $offset = 1, int $initial_value = 0, int $expiry = 0)
 * @method array getServerList()
 * @method false|array getServerByKey(string $server_key)
 * @method bool flushBuffers()
 * @method string getLastErrorMessage()
 * @method int getLastErrorCode()
 * @method int getLastErrorErrno()
 * @method false|array getLastDisconnectedServer()
 * @method false|array getStats(?string $type = null)
 * @method false|array getVersion()
 * @method false|array getAllKeys()
 * @method bool flush(int $delay = 0)
 * @method mixed getOption(int $option)
 * @method bool setOption(int $option, mixed $value)
 * @method bool setOptions(array $options)
 * @method bool setBucket(array $host_map, ?array $forward_map, int $replicas)
 * @method bool setSaslAuthData(string $username, string $password)
 * @method bool setEncodingKey(string $key)
 * @method bool isPersistent()
 * @method bool isPristine()
 * @method bool checkKey(string $key)
 */
interface MemcachedTemplate {

}